In [1]:
import numpy as np;

In [2]:
def down_sample_array(array ,sample_factor):
    array = np.array(array, dtype=float)
    array = array[::sample_factor]
    if (len(array.shape) == 2):
        array = array.transpose()
        array = array[::sample_factor]
    return array

In [3]:
def convolve(array, kernel):
    array = np.array(array, dtype=float)
    res = np.convolve(np.array(array),np.array(kernel), mode='full')
    return res[len(kernel) - 1::]

In [4]:
def fried_model_gradient(image):
    X = np.array(image, dtype=float)
    Y = np.array(image, dtype=float)
    H_h = np.array([1,-1])
    H_l = np.array([1, 1])
    for i in range(len(image)):
        X[i,:] = convolve(X[i,:],H_h)
        Y[:,i] = convolve(Y[:,i],H_h)
    for i in range(len(image)):
        X[:,i] = convolve(X[:,i],H_l)
        Y[i,:] = convolve(Y[i,:],H_l)
    return X * 0.5, Y * 0.5

In [5]:
def up_2(array):
    return np.hstack([array[:, None], np.zeros((len(array), 1))]).ravel()

In [107]:
from scipy import signal


In [30]:
import numpy as np
N = 10
a = np.random.rand(N,N)
b = np.zeros((N,N + 1))
b[:,1:] = a

In [26]:
exmpl = np.array(([[5, 7, 5, 4, 6, 0, 0, 6],
       [5, 4, 9, 3, 6, 9, 7, 0],
       [4, 1, 1, 5, 8, 0, 5, 7],
       [1, 8, 9, 2, 4, 4, 9, 9],
       [0, 4, 3, 2, 7, 1, 0, 4],
       [3, 7, 7, 7, 1, 9, 0, 3],
       [9, 5, 3, 9, 8, 7, 5, 9],
       [2, 0, 7, 6, 2, 8, 8, 2]]))

In [45]:
col = np.zeros(8)
(col ).astype(int)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
X = np.column_stack((col,exmpl))
print(X[:,:])
print(X[:,1:])

[[ 0.  5.  7.  5.  4.  6.  0.  0.  6.]
 [ 0.  5.  4.  9.  3.  6.  9.  7.  0.]
 [ 0.  4.  1.  1.  5.  8.  0.  5.  7.]
 [ 0.  1.  8.  9.  2.  4.  4.  9.  9.]
 [ 0.  0.  4.  3.  2.  7.  1.  0.  4.]
 [ 0.  3.  7.  7.  7.  1.  9.  0.  3.]
 [ 0.  9.  5.  3.  9.  8.  7.  5.  9.]
 [ 0.  2.  0.  7.  6.  2.  8.  8.  2.]]
[[ 5.  7.  5.  4.  6.  0.  0.  6.]
 [ 5.  4.  9.  3.  6.  9.  7.  0.]
 [ 4.  1.  1.  5.  8.  0.  5.  7.]
 [ 1.  8.  9.  2.  4.  4.  9.  9.]
 [ 0.  4.  3.  2.  7.  1.  0.  4.]
 [ 3.  7.  7.  7.  1.  9.  0.  3.]
 [ 9.  5.  3.  9.  8.  7.  5.  9.]
 [ 2.  0.  7.  6.  2.  8.  8.  2.]]


In [47]:
from scipy.signal import convolve2d as conv2d
def convolve_2d(array_2d, kernel, mode):
    res = np.array(array_2d, dtype=float)
    kernel = np.array(kernel)
    if (mode == 'horizontal'):
        res = conv2d(res, kernel[None, :])
        res = res[:,len(kernel)-1:]
    if (mode == 'vertical'):
        res = conv2d(res, kernel[:, None])
        res = res[len(kernel)-1:,:]
    return res

In [ ]:
convolve_2d(exmpl, H_l, )