In [24]:
import lib
import numpy as np
import pywt
H_h = np.array([1, -1])/np.sqrt(2)
H_l = np.array([1, 1])/np.sqrt(2)
G_l = H_l
G_h = -H_h

In [3]:
exmpl = np.array(([[5, 7, 5, 4, 6, 0, 0, 6],
       [5, 4, 9, 3, 6, 9, 7, 0],
       [4, 1, 1, 5, 8, 0, 5, 7],
       [1, 8, 9, 2, 4, 4, 9, 9],
       [0, 4, 3, 2, 7, 1, 0, 4],
       [3, 7, 7, 7, 1, 9, 0, 3],
       [9, 5, 3, 9, 8, 7, 5, 9],
       [2, 0, 7, 6, 2, 8, 8, 2]]))

In [33]:
exmpl

array([[5, 7, 5, 4, 6, 0, 0, 6],
       [5, 4, 9, 3, 6, 9, 7, 0],
       [4, 1, 1, 5, 8, 0, 5, 7],
       [1, 8, 9, 2, 4, 4, 9, 9],
       [0, 4, 3, 2, 7, 1, 0, 4],
       [3, 7, 7, 7, 1, 9, 0, 3],
       [9, 5, 3, 9, 8, 7, 5, 9],
       [2, 0, 7, 6, 2, 8, 8, 2]])

In [34]:
X, Y = lib.fried_model_gradient(exmpl)

In [37]:
#nextX
tmp = lib.convolve_2d(X, H_l, 'horizontal')
tmp = lib.convolve_2d(tmp, H_l, 'horizontal')
tmp = lib.convolve_2d(tmp, np.array([1, 0, 1]) / np.sqrt(2), 'vertical')
X = lib.down_sample(tmp, 2) * np.sqrt(2)
X

array([[  7.50000000e-01,   2.00000000e+00,   3.50000000e+00,
          2.25000000e+00],
       [ -2.50000000e-01,  -5.00000000e-01,  -2.50000000e-01,
         -3.14018492e-16],
       [  1.50000000e+00,   7.50000000e-01,  -3.00000000e+00,
         -2.50000000e-01],
       [ -1.07500000e+01,  -9.25000000e+00,  -7.75000000e+00,
         -6.00000000e+00]])

In [41]:
lib.down_sample(X, 2)#1 раз верно

array([[ 0.75,  1.5 ],
       [ 3.5 , -3.  ]])

In [42]:
buf = pywt.dwt2(pywt.dwt2(exmpl, 'haar')[0], 'haar')[0]

In [47]:
pywt.dwt2(buf,'haar')

(array([[ 37.625]]), (array([[ 0.625]]), array([[-0.875]]), array([[-0.875]])))

In [44]:
tmp = lib.convolve_2d(X, H_l, 'horizontal')
tmp = lib.convolve_2d(tmp, H_l, 'horizontal')
tmp = lib.convolve_2d(tmp, np.array([1, 0, 1]) / np.sqrt(2), 'vertical')
X = lib.down_sample(tmp, 2) * np.sqrt(2)
X

array([[  4.12500000e+00,   8.88178420e-16],
       [  2.25000000e+00,  -1.75000000e+00]])

In [48]:
lib.down_sample(X, 2)

array([[ 4.125]])

In [52]:
tmp  = lib.convolve_2d(Y, np.array([1,0,1])/np.sqrt(2),'horizontal')
tmp  = lib.convolve_2d(tmp, np.array([1,0,0,0,1])/np.sqrt(2),'horizontal')
tmp  = lib.convolve_2d(tmp, H_l,'vertical')
tmp  = lib.convolve_2d(tmp, H_l,'vertical')
tmp  = lib.convolve_2d(tmp, np.array([1,0,1])/np.sqrt(2),'vertical')
tmp  = lib.convolve_2d(tmp, np.array([1,0,1])/np.sqrt(2),'vertical')




In [56]:
2*lib.down_sample(tmp, 8)

array([[-0.625]])

In [57]:
def GetH_l(pow_):
    res = np.zeros(pow_ + 1)
    res[0] = res[-1] = 1
    return res

In [68]:
def GetH_h(pow_):
    res = np.zeros(pow_ + 1)
    res[0] = 1
    res[-1] = -1
    return res

In [104]:
def GetLH(m, Y):
    coef = np.power(np.sqrt(2), (m - 1))
    tmp = Y
    for i  in range (1, m):
        tmp = lib.convolve_2d(tmp, GetH_l(i), 'horizontal')
    for i in range (m - 1):
        tmp = lib.convolve_2d(tmp, GetH_l(i), 'vertical')
        tmp = lib.convolve_2d(tmp, GetH_l(i), 'vertical')
    return coef * lib.down_sample(tmp, 2 ** m)

In [108]:
GetLH(1, Y)

array([[-1.5,  2. ,  3. , -6. ],
       [ 1.5,  2.5,  4.5,  0.5],
       [ 4.5,  0. ,  1. , -2.5],
       [ 0.5,  3. , -0.5, -2. ]])

array([[ 1.75,  3.5 ,  0.5 , -1.5 , -2.25, -2.  ,  1.25,  2.  ],
       [-0.25,  0.25,  0.  , -0.25,  1.75, -0.25, -4.75, -3.  ],
       [ 0.5 , -2.  ,  1.  ,  1.5 ,  0.5 ,  0.  , -1.75, -0.75],
       [ 2.25,  1.  ,  1.  ,  1.5 ,  1.25,  3.75,  6.25,  2.75],
       [-4.5 , -2.  , -2.  , -2.  , -1.75, -1.  , -0.75, -1.5 ],
       [-1.5 , -0.25, -2.75, -4.25, -3.75, -4.75, -5.25, -2.  ],
       [ 3.  ,  0.25, -0.25,  2.25,  1.25, -1.  ,  1.  ,  1.75],
       [ 0.5 ,  1.75,  3.25,  2.  ,  2.5 ,  4.  ,  2.5 ,  0.5 ]])